const SEED_POSTS = [
  {
    id: 'seed_1',
    title: 'Pet dni v Dubrovniku brez gneče',
    excerpt: 'Mestno obzidje ob osmih zjutraj. Trajekt na Lokrum opoldne. Večerja v Konavlah, štirideset minut proti jugu, kamor ne zaide noben turistični avtobus. Lokalni vodič po Dubrovniku poleti.',
    body: '<p>Vsi prispejo ob istem času. Križarke privezejo ob desetih, izlijejo potnike na Stradun in odplujejo ob štirih popoldne. Mesto je na obeh koncih tega okna popolnoma drugačno.</p><h2>Obzidje ob zori</h2><p>Vrata se odprejo ob osmih. Do pol desetih prispe vročina skupaj s prvimi skupinami. Preteči celoten krog — 1,9 km — preden senca izgine z vzhodnega dela. Razgledi nad starim pristaniščem so zjutraj vseeno lepši.</p><h2>Zapusti staro mesto</h2><p>Otok Lokrum je petnajst minut s trajektom. Tamkajšnji pavlini se za turiste zares ne zmenijo. Vzemi s seboj kosilo. Restavracija na otoku je draga, hrana pa solidna — a ne to si prišel iskat.</p><h2>Jedi v Konavlah</h2><p>Dolina južno od Dubrovnika daje najboljše vino na Hrvaškem in jo skoraj nihče ne obišče. Konavoski dvori pri izviru reke Ljute postrežejo z jagnjetino, pečeno pod peko — tradicionalnim zvonastim pokrovom, pokopanim v žerjavici. Rezerviraj vnaprej. Domov se vrni po sončnem zahodu, ko je obalna cesta prazna.</p>',
    category: 'destination',
    sponsored: false,
    sponsorName: '',
    author: 'Uredništvo Via',
    authorInitials: 'VE',
    date: new Date(Date.now() - 86400000 * 7).toISOString(),
    image: 'https://images.unsplash.com/photo-1555990793-da11153b2473?w=900&q=80',
    featured: true,
  },
  {
    id: 'seed_2',
    title: 'Vlak iz Ljubljane na Dunaj: počasneje je bolje',
    excerpt: 'Štiri ure na regionalnem vlaku skozi dolino Save. Zakaj ICE zamudi vse, kar je vredno videti, in kaj početi na Zidanem Mostu, ko zamuja tvoja zveza.',
    body: '<p>Hitri vlak potrebuje 2 uri in 20 minut ter vozi večino poti skozi predore. Regionalni prek Zidanega Mosta vzame štiri ure in sledi reki Savi skozi dolino brez ceste — samo tirnice.</p><p>Sedi na desni strani, ko voziš proti severu. Reka se prikazuje in izginja. Na Zidanem Mostu — kjer se Sava sreča s Savinjo — je razpotje, ki izgleda točno kot kulisa vohunskega filma iz šestdesetih. Če zamuja tvoja zveza, pojdi peš do sotočja. Sedem minut hoje.</p><blockquote>Vozovnica stane 12 €. ICE stane 60 €. Razlika ni sorazmerna.</blockquote><h2>Kaj vzeti s seboj</h2><p>Sendviči na slovenskih železniških postajah so boljši, kot bi pričakoval. Kava pride v papirnatem lončku, ki malce pušča. Prinesi svojo, če ti je mar. Razgledi čez Štajersko v zadnji uri pred Dunajem so dovolj dobri, da ostaneš buden.</p>',
    category: 'tips',
    sponsored: false,
    sponsorName: '',
    author: 'Uredništvo Via',
    authorInitials: 'VE',
    date: new Date(Date.now() - 86400000 * 14).toISOString(),
    image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=900&q=80',
    featured: false,
  },
  {
    id: 'seed_3',
    title: 'Pafos: kar ti v brošuri ne povedo',
    excerpt: 'Mozaiki Unesco v Kato Pafosu so resnično svetovnega razreda. Plažni klubi niso. Praktičen vodič za štiri dni v zahodnem Cipru.',
    body: '<p>Mozaiki Unesco v Kato Pafosu sodijo med najboljše rimske tlakovanine v Sredozemlju. Ležijo v arheološkem parku na prostem, deset minut hoje od pristanišča. Vstopnina je 4,50 €. V torek zjutraj septembra jih boš imel skoraj povsem zase.</p><h2>Pristaniško območje</h2><p>Pafossko pristanišče obkrožajo restavracije, ki so solidne, a ne izjemne. Pojdi deset minut v notranjost mesta in cene se prepolovijo, kakovost pa ostane podobna. Pokrita tržnica na ulici Agoras je vredna pol ure tvojega časa že samo zavoljo pridelkov.</p><h2>Kako se premikati</h2><p>Najem avtomobila je poceni (okrog 25 €/dan) in nujen za vse izven mesta. Cesta na polotok Akamas je v zadnjem delu makadamska — primerna za manjši terenec ali samozavestnega voznika s hatchbackom. Izlet z ladjo do Modre lagune stane 35 € in vključuje kosilo. Enkrat se splača.</p>',
    category: 'destination',
    sponsored: false,
    sponsorName: '',
    author: 'Uredništvo Via',
    authorInitials: 'VE',
    date: new Date(Date.now() - 86400000 * 21).toISOString(),
    image: 'https://images.unsplash.com/photo-1557456170-0cf4f4d0d362?w=900&q=80',
    featured: false,
  },
  {
    id: 'seed_5',
    title: 'Postojnska jama: kaj vedeti, preden greš pod zemljo',
    excerpt: 'Štiriindvajset kilometrov jam, sto let star vlakec in edina jamska vretenčarka na svetu. Vse, kar potrebuješ za obisk najpomembnejše naravne znamenitosti v Sloveniji.',
    body: '<p>Postojnska jama ni turistična past v preobleki naravnega čudeža. Ravno obratno — gre za pravo geološko čudo, ki privabi milijon obiskovalcev na leto. Jama je dolga 24 kilometrov in je največja kraška jama v Evropi, odprta za javnost. Obiskovalce sprejema od leta 1819 — med prvimi organiziranimi skupinami so bili Napoleonovi vojaki. Električna razsvetljava je bila nameščena, preden so postavili Eifflov stolp.</p><h2>Praktične informacije</h2><p>Vstopnina vključuje 4 km vožnje z jamskim vlakom — enim najstarejših podzemnih vlakov na svetu — in 1,7 km vodenega ogleda peš. Celoten obisk traja okoli 90 minut. Temperatura v jami je skozi vse leto stalna 10 °C, kar avgusta preseneti. Prinesi tanek plašč ne glede na vreme zunaj.</p><p>Vstopnice kupi na spletu, preden prideš. Poleti so vrste za vstopnice na licu mesta dolge, urniki pa se zapolnijo že dopoldne. Uradna stran je postojnska-jama.eu — ne kupuj pri preprodajalcih z doplačilom.</p><h2>Proteus anguinus</h2><p>V jami živi Proteus anguinus, človeška ribica: slepa, bleda, na jamsko življenje prilagojena dvoživka, ki lahko živi več kot sto let in preživi leta brez hrane. Je edina jamska vretenčarka, ki izvira iz Evrope. Postojnski vzrejni program je vzredil na stotine teh živali. Videl jih boš v vivariju med sprehodom — majhne, prosojne, docela čudne. Nič drugega ne izgleda tako.</p><blockquote>Slovenci ji pravijo "človeška ribica" — ker njena bleda, skoraj prosojna koža spominja na človeško meso. Ko jo enkrat vidiš, ime dobi neprijetno logičen smisel.</blockquote><h2>Predjamski grad</h2><p>Devet kilometrov od Postojne stoji Predjamski grad, zgrajen neposredno v ustje skalne votline na polovici 123-metrske pečine. Izgleda izmišljeno. Ni. Sedanja zgradba izvira iz 16. stoletja. Kombinirana vstopnica za Postojnsko jamo in Predjamo je vredna cene, obisk obeh v enem dnevu pa je povsem izvedljiv — vožnja traja dvanajst minut.</p><h2>Kako priti</h2><p>Postojna je uro vožnje od Ljubljane (54 km po avtocesti A1). Z avtobusom vozita Nomago in FlixBus neposredno z Avtobusne postaje Ljubljana, pot traja okoli 1 h 15 min. Vhod v jamo je pet minut hoje od avtobusne postaje v Postojni. Do Predjamskega gradu z javnim prevozom ni dostopa — vzemi avto ali dodaj grad k rezervaciji prek sistema Postojnske jame, ki vključuje prevoz.</p>',
    category: 'destination',
    sponsored: false,
    sponsorName: '',
    author: 'Uredništvo Via',
    authorInitials: 'VE',
    date: new Date(Date.now() - 86400000 * 2).toISOString(),
    image: 'https://images.unsplash.com/photo-1756320689173-227422d1280a?w=900&q=80',
    featured: true,
  },
  {
    id: 'seed_6',
    title: 'Prekmurje: del Slovenije, o katerem nihče ne govori',
    excerpt: 'Ravno, tiho in trmasto pri svojem načinu življenja. Severovzhodni kot Slovenije ima termalne kopeli, svojsko kuhinjo in tempo, ki se popolnoma razlikuje od preostale države.',
    body: '<p>Večina tistih, ki obiščejo Slovenijo, naredi enako zanko: Ljubljana, Bled, Piran. To je dobra zanka. A obstaja regija na severovzhodu — ob meji z Avstrijo, Madžarsko in Hrvaško — ki deluje na povsem drugi frekvenci. Prekmurje je edini del Slovenije, ki leži čez reko Muro, in je bil stoletja geografsko ter kulturno odrezan od preostale države. To začutiš takoj.</p><h2>Pokrajina</h2><p>Prekmurje je ravno. Julijskih Alp tu ni videti. Teren je kmetijski — sončnice, bučke, koruzna polja v dolgih vrstah — ki ga na severu prekinjajo Goričko gričevje, nežno, poraščeno z gozdom in skoraj brez turistov. To je pokrajina, ki se odpre počasnemu gibanju: kolesarjenje med vasmi, postanki na kmetijah, brezskrbno popoldne v termalni kopeli.</p><h2>Hrana</h2><p>Prekmurska kuhinja je dovolj samosvoja, da ti Ljubljančani povedo, da je skoraj madžarska. Niso daleč od resnice. Bograč je mesna enolončnica, počasi kuhana s tremi vrstami mesa in papriko — težka, okrepčilna, ne podobna ničemer, kar bi jedel v Ljubljani. Gibanica je regionalna večplastna pita, polnjena z makom, orehi, skuto in jabolki, pečena skupaj v izmenjujočih se plasteh. Naroči jo povsod.</p><blockquote>Prekmurska gibanica je zaščitena z oznako EU kot tradicionalna posebnost. Potovanja ne prenaša dobro. Jej jo tukaj.</blockquote><p>V Murski Soboti, regionalnem središču, sobotna tržnica prodaja bučno olje — stiskano iz praženih semen, temnozeleno, z okusom po oreških — ki ga boš hotel odnesti domov v steklenici. Paše k vsemu.</p><h2>Terme Banovci in Terme 3000</h2><p>Tamkajšnje terme niso luksuzni resorti. So veliki, domači, družinam prijazni kraji, kamor Slovenci in Madžari prihajajo za vikend, da se v topli mineralni vodi sprostijo brez posebnega programa. Terme Banovci pri Veržeju imajo bolj tiho, podeželsko vzdušje. Terme 3000 v Moravskih Toplicah so večje in bolj urejene. Obe staneta precej pod 20 € za cel dan. Zunaj vrhunca poletne sezone rezervacije ni treba narejati daleč vnaprej.</p><h2>Kako priti</h2><p>Murska Sobota je 190 km od Ljubljane — okrog dve uri z avtom po avtocestah A1 in A5. Z vlakom pot traja okoli 2 h 45 min s prestopom v Pragerskem, vlaki vozijo tri- do štirikrat na dan. Izvedljivo je, a avto ti da več svobode. Nastani se v Murski Soboti ali okolici in Goričko ter terme obiskuj kot dnevne izlete. Dve noči zadostujeta, da razumeš, kaj je ta regija. Tri noči so boljše.</p>',
    category: 'destination',
    sponsored: false,
    sponsorName: '',
    author: 'Uredništvo Via',
    authorInitials: 'VE',
    date: new Date(Date.now() - 86400000 * 1).toISOString(),
    image: 'https://images.unsplash.com/photo-1535222830855-fd60aca7e065?w=900&q=80',
    featured: false,
  },
  {
    id: 'seed_4',
    title: 'Zakaj priporočamo rezervacijo nastanitve vsaj 6 tednov vnaprej',
    excerpt: 'Partnerska zgodba: kako zgodnje načrtovanje vpliva na to, kaj ti je sploh na voljo — in zakaj je to pomembnejše v predsezonskem obdobju kot v poletni konici.',
    body: '<p>To je partnerska zgodba, napisana v sodelovanju z Booking.com. Via zasluži provizijo, ko rezerviraš prek naših povezav, brez dodatnih stroškov za tebe. Izpostavljamo le partnerje, katerih storitve sami uporabljamo.</p><h2>Podatki</h2><p>Podatki Booking.com za evropske destinacije kažejo, da so nastanitve z oceno 8,5 ali več v predsezonskem obdobju (maj–junij, september–oktober) praviloma popolnoma zasedene 6–8 tednov pred prihodom. V glavni sezoni (julij–avgust) se to okno za obalne destinacije podaljša na 10–12 tednov.</p><h2>Kaj to pomeni v praksi</h2><p>Če prideš na Santorini avgusta z rezervacijo dva tedna vnaprej, izbiraš med tistim, kar je ostalo. Kar je pogosto povsem sprejemljiva soba — a ne tista s pogledom na kaldero, po ceni, ki si jo načrtoval.</p><blockquote>Zgodnje načrtovanje ni stvar tesnobe. Gre za to, da imaš možnosti.</blockquote><p>Motor za itinerarje Via privzeto pripravi možnosti nastanitev z neposrednimi povezavami za rezervacijo. Priporoča se, da te povezave odpreš takoj, ko je tvoj itinerar pripravljen — ne dva tedna pred odhodom.</p>',
    category: 'partner',
    sponsored: true,
    sponsorName: 'Booking.com',
    author: 'Via x Booking.com',
    authorInitials: 'VB',
    date: new Date(Date.now() - 86400000 * 3).toISOString(),
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=900&q=80',
    featured: false,
  },
]
